-- Enable pgcrypto extension to generate UUIDs
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Master Data Tables
-- These tables store your primary lists of owners, customers, etc.

CREATE TABLE owners (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz default now()
);

CREATE TABLE customers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz default now()
);

CREATE TABLE items (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz default now()
);

CREATE TABLE suppliers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz default now()
);

CREATE TABLE expense_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz default now()
);

-- Transactional Data Tables
-- These tables store the entries for sales, purchases, etc.
-- We use UUID for primary keys to allow for reliable client-side ID generation.

CREATE TABLE entries (
  id uuid default gen_random_uuid() primary key,
  "Date" date,
  "Bill No" text,
  "Owner" text,
  "Customer" text,
  "Item" text,
  "Mark" text,
  "N" text,
  "Pkgs" numeric,
  "P.Kilo" numeric,
  "G.Kilo" numeric,
  "Tare" numeric,
  "N.Kilo" numeric,
  "Rate" numeric,
  "Kooli" numeric,
  "C.Amount" numeric,
  "A.Amount" numeric,
  "Cash" numeric,
  "Cheque" numeric,
  "Credit Given" numeric,
  "Credit Received"numeric,
  "Balance" numeric,
  "Remark" text,
  created_at timestamptz default now()
);

CREATE TABLE purchases (
  id uuid default gen_random_uuid() primary key,
  date date,
  "billNo" text,
  supplier text,
  item text,
  qty numeric,
  rate numeric,
  amount numeric,
  extra numeric,
  "paidCash" numeric,
  "paidCheque" numeric,
  credit numeric,
  balance numeric,
  remark text,
  created_at timestamptz default now()
);

CREATE TABLE expenses (
  id uuid default gen_random_uuid() primary key,
  date date,
  category text,
  description text,
  amount numeric,
  mode text,
  "paidTo" text,
  type text,
  ref text,
  created_at timestamptz default now()
);

CREATE TABLE cheques (
  id uuid default gen_random_uuid() primary key,
  date date,
  "chequeNo" text,
  bank text,
  party text,
  amount numeric,
  type text,
  status text,
  "clearDate" date,
  remark text,
  created_at timestamptz default now()
);